version: '3.1'

services:
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: my-secret-password
      POSTGRES_USER: khritik
      POSTGRES_DB: ecommerce
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432